node()
{
	stage('gitlab pull')
	{
		//checkout scm
		checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkins_ssh', url: 'http://gitlab.antlinux.local/antman/data_center.git']]])
	}
	stage('env')
	{
		env
		sh('env')
	}
	stage('commit-hash')
	{
		echo "ANTMAN: env.GIT_COMMIT ${env.GIT_COMMIT}"
		echo "ANTMAN: scmVars.GIT_COMMIT ${scmVars.GIT_COMMIT}"
		echo "${scmVars}"
	}	
}
