---
version: "3.4"
services:
  plex:
    image: linuxserver/plex
    container_name: plex   
    environment:
      - PUID=1000
      - PGID=100
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
      - LOCAL_NETWORK=10.0.0.0/8
    ports:
      - 32400:32400
      - 1900:1900
      - 3005:3005    
      - 5353:5353
      - 32410:32410
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - /mnt/media/appdata/plex:/config
      - /mnt/media/media/tv:/tv
      - /mnt/media/media/movies:/movies
      - /mnt/media/media/music:/music
    restart: unless-stopped
