node()
{

    def gitlab_trigger_branch = params.getOrDefault("BUILD_BRANCH", "main")
	all_stages = [:]
	all_stages['ansible'] = {
					stage('Build docker-ansible')
					{
						build job: "docker/ansible/build"
					}
				}
	
	all_stages['docker_terraform'] = {
					stage('Build docker-terraform')
					{
						build job: "docker/terraform/build"
					}
				}

        all_stages['docker_consul'] = {
                                        stage('Build docker-consul')
                                        {
                                                build job: "docker/consul/build"
                                        }
                                }

        all_stages['docker_vault'] = {
                                        stage('Build docker-vault')
                                        {
                                                build job: "docker/vault/build"
                                        }
                                }

        all_stages['docker_packer'] = {
                                        stage('Build docker-packer')
                                        {
                                                build job: "docker/packer/build"
                                        }
                                }


        all_stages['packer_CentOS-7.9.2009'] = {
                                                    stage('Build packer-CentOS-7.9.2009')
                                                    {
                                                            build job: "packer/golden-baseos/centos7/CentOS-7.9.2009/build", parameters: [[$class: 'StringParameterValue', name: 'BUILD_BRANCH', value: gitlab_trigger_branch]]
                                                    }
                                                }

        all_stages['packer_CentOS-8.2.2004'] = {
                                                    stage('Build packer-CentOS-8.2.2004')
                                                    {
                                                            build job: "packer/golden-baseos/centos8/CentOS-8.2.2004/build", parameters: [[$class: 'StringParameterValue', name: 'BUILD_BRANCH', value: gitlab_trigger_branch]]
                                                    }
                                                }

        all_stages['packer_CentOS-8.4.2105'] = {
                                                    stage('Build packer-CentOS-8.4.2105')
                                                    {
                                                            build job: "packer/golden-baseos/centos8/CentOS-8.4.2105/build", parameters: [[$class: 'StringParameterValue', name: 'BUILD_BRANCH', value: gitlab_trigger_branch]]
                                                    }
                                                }


    stage ('Print ENV')
    {
        sh('env')
        print(params)
        print ("gitlab_trigger_branch = ${gitlab_trigger_branch}")
    }
    stage('Build docker-ubi8-hardened')
    {
            build job: 'docker/ubi8/build'
    }

	stage('Build All')
	{
		parallel(all_stages)
	}


	/*stage('Build packer-CentOS-7.9.2009')
    {
            build job: "packer/golden-baseos/centos7/CentOS-7.9.2009/build', parameters: [[$class: 'StringParameterValue', name: 'BUILD_BRANCH', value: gitlab_trigger_branch]]
    }

    stage('Build packer-CentOS-8.2.2004')
    {
            build job: "packer/golden-baseos/centos8/CentOS-8.2.2004/build', parameters: [[$class: 'StringParameterValue', name: 'BUILD_BRANCH', value: gitlab_trigger_branch]]
    }

    stage('Build packer-CentOS-8.4.2105')
    {
            build job: "packer/golden-baseos/centos8/CentOS-8.4.2105/build', parameters: [[$class: 'StringParameterValue', name: 'BUILD_BRANCH', value: gitlab_trigger_branch]]
    }*/

	/*properties([ 	disableConcurrentBuilds(),
    			gitLabConnection(gitLabConnection: 'gitlab1', jobCredentialId: ''),
    			parameters([string(defaultValue: 'main', name: 'BUILD_BRANCH')])
    			])*/
}
