apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-antlinux-local
  namespace: vault
spec:
  secretName: vault-antlinux-local-tls
  issuerRef:
    name: vault-issuer
  commonName: vault.antlinux.local
  dnsNames:
  - vault.antlinux.local
