node()
{

	stage('Download Repo')
	{
		checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/antman25/data_center.git']]])
	}
	stage('Env Dump')
	{
		sh ('env | sort')
	}
	stage('Stage 1 Test')
	{
		sh("${WORKSPACE}/rpm-library/rpmbuild/build.sh")
	} 
	stage('Stage 2 Test')
	{
		echo('asdf')
	}
}

