apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-antlinux-org
  namespace: sonarqube
spec:
  secretName: sonarqube-antlinux-org-tls
  issuerRef:
    name: vault-issuer
  commonName: sonarqube.antlinux.org
  dnsNames:
  - sonarqube.antlinux.org
