apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-antlinux-local
  namespace: sonarqube
spec:
  secretName: sonarqube-antlinux-local-tls
  issuerRef:
    name: vault-issuer
  commonName: sonarqube.antlinux.local
  dnsNames:
  - sonarqube.antlinux.local
