apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-default-consul-server-0
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
