apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-postgresql-0
  labels:
    type: local
spec:
  storageClassName: fast-disks
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
