apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-default-consul-consul-server-1
  labels:
    type: local
spec:
  storageClassName: fast-disks
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
