version: '2.1'
services:
 transmission-openvpn:
    volumes:
        - /mnt/media/downloads/:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1000
        - PGID=100
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=NORDVPN
        # - OPENVPN_CONFIG=default
        - NORDVPN_COUNTRY=US
        - NORDVPN_CATEGORY=legacy_p2p
        - NORDVPN_PROTOCOL=udp
        - OPENVPN_USERNAME=${NORDVPN_USERNAME}
        - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=10.0.0.0/8
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        - 9117:9117
        - 7878:7878
        - 8989:8989
        - 8686:8686
        - 5299:5299
    restart: always
    image: haugene/transmission-openvpn

 jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: "service:transmission-openvpn"
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/Denver
        - AUTO_UPDATE=true #optional
        - RUN_OPTS=#optional
    volumes:
        - /mnt/media/appdata/jackett:/config
        - /mnt/media/downloads/watch:/downloads
    restart: unless-stopped

 radarr:
    image: linuxserver/radarr
    network_mode: "service:transmission-openvpn"
    container_name: radarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/Denver
        - UMASK_SET=022 #optional
    volumes:
        - /var/lib/media_automation/radarr:/config
        - /mnt/media/media/movies:/movies
        - /mnt/media/downloads/completed:/data/completed
    restart: unless-stopped

 sonarr:
    image: linuxserver/sonarr
    network_mode: "service:transmission-openvpn"
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/Denver
        - UMASK_SET=022 #optional
    volumes:
        - /var/lib/media_automation/sonarr:/config
        - /mnt/media/media/tv:/tv
        - /mnt/media/downloads/completed:/data/completed
        - /mnt/media/downloads/trash:/trash
    restart: unless-stopped

