---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-agent
  namespace: default
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
