node()
{
	stage('gitlab clone')
	{
		checkout scm
	}
	
        stage('build jobs')
        {
		 folder('build-root')
                 jobDsl targets: ['jenkins-library/dsl/jobs/docker_ansible.groovy'].join('\n'),
                 removedJobAction: 'DELETE',
                 removedViewAction: 'DELETE',
                 lookupStrategy: 'SEED_JOB',
                 additionalParameters: [message: 'Hello from pipeline', credentials: 'SECRET']
        }
}
