node()
{
	stage('gitlab clone')
	{
		checkout scm
	}
	
        stage('Create Jobs')
        {
                 jobDsl targets: ['jenkins-library/dsl/jobs/build_root.groovy', 
				  'jenkins-library/dsl/jobs/docker_ansible.groovy',
				  'jenkins-library/dsl/jobs/docker_terraform.groovy',
				  'jenkins-library/dsl/jobs/docker_consul.groovy',
   				  'jenkins-library/dsl/jobs/docker_vault.groovy'].join('\n'),
                 removedJobAction: 'DELETE',
                 removedViewAction: 'DELETE',
                 lookupStrategy: 'SEED_JOB',
                 additionalParameters: [message: 'Hello from pipeline', credentials: 'SECRET']
        }
	stage('Run Build Jobs')
	{
		build job: '/build-root/build-master'
	}
}
