node()
{
        stage('build jobs')
        {
                 jobDsl targets: ['jenkins-library/dsl/jobs/docker-ansible.groovy'].join('\n'),
                 removedJobAction: 'DELETE',
                 removedViewAction: 'DELETE',
                 lookupStrategy: 'SEED_JOB',
                 additionalParameters: [message: 'Hello from pipeline', credentials: 'SECRET']
        }
}
