apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
spec:
  secretName: tls-certificate
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: vault.antlinux.org

  dnsNames:
    - vault.antlinux.org
