apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-antlinux-org
  namespace: vault
spec:
  secretName: vault-antlinux-org-tls
  issuerRef:
    name: vault-issuer
  commonName: vault.antlinux.org
  dnsNames:
  - vault.antlinux.org
  - vault-agent-injector-svc.vault.svc
  - vault-agent-injector-svc.vault
  - localhost
  - 127.0.0.1
