vm-name         = "CentOS8-Template"
vm-cpu-num      = 2
vm-mem-size     = 4096
vm-disk-size    = 10240
iso-url         = "[antlun] ISO Images/centos/CentOS-8.2.2004-x86_64-dvd1.iso"
iso-checksum    = "47dc26d76e566280cc47437fd2466134"
cluster         = "{{ env `CLUSTER` }}"
datacenter      = "{{ env `DATACENTER` }}"
datastore       = "{{ env `DATASTORE` }}"
folder          = "{{ env `FOLDER` }}"
iso-datastore   = "{{ env `ISO_DATASTORE` }}"
iso-path        = "{{ env `ISO_PATH` }}"
network         = "{{ env `NETWORK` }}"
vm-name         = "{{ env `BASE_VM_TEMPLATE_NAME` }}"
vsphere-server  = "{{ env `VCENTER_SERVER` }}"
vsphere-user    = "{{ env `VCENTER_USER` }}"
vsphere-password = "{{ env `VCENTER_PASSWORD` }}"
ssh-username    = "{{ env `VCENTER_USER` }}"
ssh-password = "{{ env `VCENTER_PASSWORD` }}"