apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-antlinux-org
  namespace: nexus
spec:
  secretName: nexus-antlinux-org-tls
  issuerRef:
    name: vault-issuer
  commonName: nexus.antlinux.org
  dnsNames:
  - nexus.antlinux.org
  - nexus.antlinux.local
  - docker.antlinux.org
  - docker.antlinux.local

