apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: nexus
spec:
  vault:
    server: http://vault.vault:8200
    path: antlinux-org/v1/ica1/v1/sign/nexus-app-role
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager-role
        secretRef:
          name: issuer-token
          key: token
